sonar.projectKey=audio-sync-app
sonar.projectName=audio-sync-app
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.js,src/**/*.test.jsx
sonar.exclusions=**/*.test.js,**/*.test.jsx,**/node_modules/**,**/dist/**,**/coverage/**,**/aligned_transcript.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.test.js,**/*.test.jsx,**/main.jsx,**/setup.js
